version: '3'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - ${PWD}/.database/redis:/data
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: MariaDb!
    networks:
      - backend
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ${PWD}/.database/mariadb:/var/lib/mysql
    ports:
      - '3306:3306'
networks:
  backend:
    driver: bridge
